# Perceptron OR Implementation

## Setting up the environmentm

The Keras framework has been implemented inside the Google Tensorflow API on version 2.0. The Keras framework takes advantage of the optimizations for GPU and also TPU

The first thing we should do is to update Google Colab tensorflow version <strong>this has to be done at every notebook created</strong>. The tool we'll be using for that is the `pip` tool. It is important that we restart the environment after finishing the installation;

In [1]:
! pip install tensorflow==2

     |████████████████████████████████| 86.3MB 86kB/s  eta 0:00:011    |█████████████████████████▌      | 68.7MB 6.3MB/s eta 0:00:03
     |████████████████████████████████| 71kB 391kB/s eta 0:00:01
     |████████████████████████████████| 61kB 396kB/s eta 0:00:01
     |████████████████████████████████| 3.8MB 2.8MB/s eta 0:00:01
     |████████████████████████████████| 450kB 3.4MB/s eta 0:00:01
     |████████████████████████████████| 1.3MB 3.5MB/s eta 0:00:01
     |████████████████████████████████| 51kB 357kB/s eta 0:00:011
     |████████████████████████████████| 112kB 7.1MB/s eta 0:00:01
     |████████████████████████████████| 2.7MB 1.1MB/s eta 0:00:01
     |████████████████████████████████| 51kB 227kB/s  eta 0:00:01
     |████████████████████████████████| 81kB 588kB/s eta 0:00:011
     |████████████████████████████████| 92kB 623kB/s eta 0:00:011
     |████████████████████████████████| 163kB 5.1MB/s eta 0:00:01
     |████████████████████████████████| 81kB 601kB/s  eta 0:00:01
     |█████

  Created wheel for absl-py: filename=absl_py-0.9.0-cp37-none-any.whl size=121932 sha256=6a7e1c4f84a02b9ae603ac1857ba26fb0b39dbf7f5a59f7f75e097ab40a41f3b
  Stored in directory: /home/hub/.cache/pip/wheels/8e/28/49/fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d
  Created wheel for termcolor: filename=termcolor-1.1.0-cp37-none-any.whl size=4832 sha256=42e90403c15575241ff63e7a17385fee088c9ebaae52cd67afbd170e97d6c435
  Stored in directory: /home/hub/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
Successfully built opt-einsum gast absl-py termcolor


In [2]:
import tensorflow as tf
print(tf.__version__) # Check the version of the tensorflow library

2.0.0


## Create the input dataset

We will also use numpy, thus the import:

In [3]:
import numpy as np

Create the truth table for the OR operation:

In [4]:
or_truth_table = np.array([[0,0,0],
                           [0,1,1],
                           [1,0,1],
                           [1,1,1]])

## Creating a Sequential Model

Import and instantiate the Sequential model

In [0]:
from tensorflow.keras.models import Sequential

In [0]:
model = Sequential()

Create a layer with a single neuron. The Dense layer represents a layer of neurons that are completely interconnected with the previous and next layer.

In [0]:
from tensorflow.keras.layers import Dense

In [0]:
model.add(Dense(units=1, input_dim=2))

Now we need to compile the model

In [0]:
model.compile(loss="mean_squared_error", optimizer="sgd")

Split our dataset into input and expected values;

In [0]:
X_data = or_truth_table[:,[0,1]]

In [0]:
Y_data = or_truth_table[:,2]

Perform the training (`fit`) operations.

In [0]:
model.fit(x=X_data, y=Y_data, epochs=200, verbose=0)

Check the error value (`loss`) when predicting using the dataset, i.e., how far off we are from the correct answer. 

In [0]:
loss_and_metrics = model.evaluate(X_data, Y_data)
print(loss_and_metrics)

4/1 [========================================================================================================================] - 0s 599us/sample - loss: 0.0819
0.08190849423408508


Now it is time to make predictions using our trained model

In [0]:
prediction = model.predict(X_data)

In [0]:
print(prediction)

[[0.28700256]
 [0.75856614]
 [0.75304747]
 [1.224611  ]]


Convert the output to the desired format:

In [0]:
print(np.round(prediction))

[[0.]
 [1.]
 [1.]
 [1.]]


In [0]:
print(Y_data)

[0 1 1 1]
